# Generated by Django 6.0 on 2026-01-13 14:58

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('uuid', models.UUIDField(default=api.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[api.models.val_sal])),
                ('type_of_salary', models.CharField(default='Monthly salary', max_length=14)),
                ('work_time', models.CharField(max_length=5)),
                ('type_of_worker', models.CharField(max_length=35)),
                ('position_type', models.CharField(choices=[('waiter', 'Waiter'), ('bartender', 'Bartender'), ('chef', 'Chef'), ('driver', 'Driver'), ('truck driver', 'Truck driver'), ('cashier', 'Cashier'), ('delivery', 'Delivery'), ('warehouse worker', 'Warehouse worker'), ('janitor', 'Janitor')], db_index=True, max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, validators=[api.models.val_pic_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=api.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the international format.', regex='^\\+?1?\\d{9,15}$')])),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='', validators=[api.models.val_pic_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
