# Generated by Django 6.0 on 2026-01-21 23:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position_type',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('bartender', 'Bartender'), ('chef', 'Chef'), ('driver', 'Driver'), ('truck_driver', 'Truck driver'), ('cashier', 'Cashier'), ('delivery', 'Delivery'), ('warehouse worker', 'Warehouse worker'), ('janitor', 'Janitor')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='salary',
            field=models.DecimalField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], db_index=True, decimal_places=2, max_digits=10, validators=[api.models.val_sal]),
        ),
    ]
