# Generated by Django 6.0 on 2026-01-21 23:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='type_of_worker',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position_type',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('bartender', 'Bartender'), ('chef', 'Chef'), ('driver', 'Driver'), ('truck_driver', 'Truck driver'), ('cashier', 'Cashier'), ('delivery', 'Delivery'), ('warehouse_worker', 'Warehouse worker'), ('janitor', 'Janitor')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='salary',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[api.models.val_sal]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type_of_salary',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='monthly', max_length=14),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='work_time',
            field=models.CharField(max_length=20),
        ),
    ]
