# Generated by Django 6.0 on 2026-01-22 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_advertisement_type_of_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the international format.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
