# Generated by Django 6.0 on 2026-03-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
