# Generated by Django 6.0 on 2026-03-01 14:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emailverification_pending_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=api.models.generate_uuid, unique=True),
        ),
    ]
