# Generated by Django 6.0 on 2026-03-01 15:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_emailverification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=api.models.generate_uuid, editable=False, unique=True),
        ),
    ]
