# Generated by Django 6.0 on 2026-03-05

import django.core.validators
from django.db import migrations, models


def backfill_ad_contact_details(apps, schema_editor):
    Advertisement = apps.get_model("api", "Advertisement")
    UserProfile = apps.get_model("api", "UserProfile")

    phone_by_user_id = {
        profile.user_id: (profile.phone_number or "").strip()
        for profile in UserProfile.objects.all().only("user_id", "phone_number")
    }

    for ad in Advertisement.objects.select_related("posted_by").all().iterator():
        fields_to_update = []

        if not ad.contact_email:
            contact_email = (ad.posted_by.email or "").strip()
            if contact_email:
                ad.contact_email = contact_email
                fields_to_update.append("contact_email")

        if not ad.contact_phone:
            contact_phone = phone_by_user_id.get(ad.posted_by_id, "")
            if contact_phone:
                ad.contact_phone = contact_phone
                fields_to_update.append("contact_phone")

        if fields_to_update:
            ad.save(update_fields=fields_to_update)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_advertisementreport_savedadvertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the international format.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.RunPython(backfill_ad_contact_details, noop_reverse),
    ]

